### ISSUE TITLE
Non-cookie session store

### ISSUE THREAD

**Issue by muirrn** [gorilla/csrf#100]
I'm working on go web server to replace a legacy rails app. I need to interoperate with the rails server for the time being. In the case of CSRF, I need to check the rails CSRF token as appropriate for requests that come to the go web server. We store our rails session in the database, not in a cookie. There doesn't seem to be a way in gorilla/csrf to control where to get/set the csrf token from other than changing the cookie name. Perhaps we can expose the "store" interface and associated option?

**Comment by elithrar** [comment]
Hey Muir,

Is there a reason you would want server-side CSRF tokens?

- Note that no state is being stored in the cookie beyond the authenticated
token itself
- Rails, Django, etc do not store CSRF tokens server side, even when
sessions are.
- The ephemeral nature of CSRF tokens, and lack of persisting state, makes
a client-side-only model far less complex.

**Comment by muirrn** [comment]
I am integrating with a pre-existing rails app that stores the CSRF token in the database. It is outside the scope of my work to change how that works. It is a very old version of rails, so maybe storing it in the session was the default behavior back then.

**Comment by muirrn** [comment]
Unless I am mistaken, rails stores the CSRF token in the session: https://github.com/rails/rails/blob/299a213a738e078c6fbddd488a711ea9bb066fe2/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L397

Can you point to where rails doesn't store CSRF token server side even when sessions are?

**Comment by elithrar** [comment]
Since Rails implements CSRF protection via the double-submit method + with BREACH mitigation (the same as this library), the idea is to match the request token (form, header) with the "session" (cookie) token. 

If you take the server-side model, then the user cookie has an ID to the token stored in (Redis, MySQL, etc). Since the token does NOT store any useful information (unlike sessions, which often have email addresses, admin status, etc.) and are authenticated (via HMAC), the value of server-side storage is extremely diminished.

It looks like Django also moved to (optionally) letting you use server-side sessions here too, but it's not the default [since the benefits are arguable].

I'm not opposed to exposing the store interface, but it's still unclear the _security_ benefits of adding to the API surface, and chance of misconfiguration.

**Comment by muirrn** [comment]
I am not claiming server side has any security benefits. I simply want to use this package to interoperate with a legacy app, and I am constrained by how the app works. I acknowledge my use case is uncommon, but I believe it is valid nonetheless.

I can respect not wanting to complicate the API with potentially dangerous configuration options. I opened this issue because the `store` interface looked like it was already designed to be pluggable, but if you don't think the time is right then please close this issue and I will make the change in a fork.

**Comment by muirrn** [comment]
Closing. Our version of rails is too old (doesn't have the pad/mask stuff, even). I will just compare them myself.
