### ISSUE TITLE
[question] General CSRF Protection and Library Questions

### ISSUE THREAD

**Issue by donaldthai** [gorilla/csrf#105]
Hi, I had a few questions regarding the library and general CSRF protection:

- This library uses the "Double-Submit" method, so that means that the token is only stored in the secure cookie and client side right? What stops an attacker from visiting a site with csrf protection setup to generate that secure cookie and masked token and forging a request for another user?

- Should the 32 byte auth key be tied to the user session to make it unique just for that particular user? Don't really see a way to do this with this library.

- Do login forms need CSRF protection? Does it make sense to generate a csrf token for it before login?

Thanks!

**Comment by donaldthai** [comment]
> > This library uses the "Double-Submit" method, so that means that the token is only stored in the secure cookie and client side right? What stops an attacker from visiting a site with csrf protection setup to generate that secure cookie and masked token and forging a request for another user?
> 
> The attacker won't have the same cookie value as the user.

I might be missing some key concepts about how "double-submit" works. Regardless if an attacker won't have the same cookie value, can't an attacker just use their cookie token value to forge a request since the server validates the unmasked and the decoded masked value?

**Comment by elithrar** [comment]
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie

The attacker can't write cookies as your domain, unless:

1) They man-in-the-middle your connection (which is a whole class of
problems - you're screwed anyway here)
2) They can read a user's cookie from malicious JavaScript inserted on your
site (i.e. a compromised JS library, or XSS attack that adds JS)

Otherwise, the user has a cookie, and your forms have a token, and they
have to match. The attacker can't see the cookie due to the same-origin
policy (unless #2), but the cookie will be submitted automatically for any
requests to your site, so a cookie alone isn't enough. In fact, that
cookies are _sent_ is exactly how CSRF attacks work: a user is logged in,
and the attack tricks them into (often passively!) performing an action on
your website that might cause harm - {transfer money, change password,
remove 2FA, post hate-speech, etc}.

So, your site ALSO embeds that value as part of the form. The attacker
can't see the form, or the cookie value, and thus can't get you to submit a
form that has a matching value.

**Comment by donaldthai** [comment]
> The attacker can't write cookies as your domain, unless:

> 1) They man-in-the-middle your connection (which is a whole class of problems - you're screwed anyway here) 
> 2) They can read a user's cookie from malicious JavaScript inserted on your site (i.e. a compromised JS library, or XSS attack that adds JS)

I see! Thank you for your informative answer!
