### ISSUE TITLE
Demo always given Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by bennAH** [gorilla/csrf#13]
Hey,

I tried to use this package and on form submission, I am getting 

'Forbidden - CSRF token invalid'

I thought it may be something to do with the way I set up my application so I used the sample application provided in the docs and I still receive the same error.

I can see the token in the hidden field is the same as that on the submitted form but differ when later retrieved and compared.

**Comment by elithrar** [comment]
Hey @bennAH — if you're running locally without HTTPS, you'll need to turn off the Secure flag on the CSRF cookie else you'll get an error (because the cookie won't be sent back to the server).

```go
	http.ListenAndServe(":8000",
		csrf.Protect([]byte("32-byte-long-auth-key"), csrf.Secure(false))(r))
```

gorilla/csrf defaults to 'true' for the Secure and HttpOnly flags on the cookie for security reasons.

I'll update the docs to make this a little clearer for those working through the examples.

**Comment by bennAH** [comment]
Thanks @elithrar for the quick response. Should have dug further into the code / docs

**Comment by elithrar** [comment]
No problems. Feel free to open an issue if you have any other questions about using the package!
