### ISSUE TITLE
can't rename fieldName

### ISSUE THREAD

**Issue by gebv** [gorilla/csrf#22]
https://github.com/gorilla/csrf/blob/master/helpers.go#L54

fieldName ignores settings?
csrf.FieldName("authenticity_token")

**Comment by elithrar** [comment]
Changing the FieldName changes the name of the form field inspected on a
request: https://github.com/gorilla/csrf/blob/master/helpers.go#L102

It does not currently change it when using the TemplateField helper,
because the helper can't access the cs.opts.FieldName directly.

I'm considering making a change that passes the FieldName in the request
context, but until then just make a copy of TemplateField that uses your
name instead of the package default.

**Comment by gebv** [comment]
i understood. thank
