### ISSUE TITLE
Why is each CSRF token only valid for one path?

### ISSUE THREAD

**Issue by natemara** [gorilla/csrf#32]
If I want to protect the `POST /user/register` path with CSRF, I am required to get a CSRF token by performing `GET /user/register`. A token issued from `GET /ping` is not valid, even if it is the last request issued. Why is this? Also, why is the same token valid for multiple requests?

**Comment by elithrar** [comment]
* Use [`csrf.Path`](https://godoc.org/github.com/gorilla/csrf#Path) to specify the cookie path - e.g. `/` - to issue CSRF cookies as. Cookies will otherwise be automatically scoped to the path they are issued from (the default browser behaviour)
* Tokens are valid for multiple requests to prevent multiple tabs/windows from breaking. If the token was reset after each request, this would break. This (not resetting per-request) is the same behaviour that Rails/Django/many other well-tested libraries use, with the added benefit that gorilla/csrf *masks* the token per-request to prevent against capturing secrets via the BREACH attack.

Hope that clarifies.

**Comment by natemara** [comment]
Thank you very much.
