### ISSUE TITLE
Option to make it not consume http body; verify token manually

### ISSUE THREAD

**Issue by sinni800** [gorilla/csrf#67]
I have a site where large file uploads through FORMs will be done, thus it would be preferable to first manually parse the request, streaming files out (incase of multipart/form-data), then to call csrf, asking if the request is okay. Reading the request before csrf gets to it (and consumes it) seems excessive.

**Comment by elithrar** [comment]
I've left this on the backlog for a while, as manually validating is extremely risky (i.e. if you forget, you have nothing).

What would you expect the API to look like for this? Note that gorilla/csrf still needs to inject an instance of itself into the request, so that you can call (e.g.) `csrf.Verify(r, w)` in your handler after processing.

**Comment by elithrar** [comment]
Closing for now, as this has come up rarely.
