### ISSUE TITLE
Skipping CSRF check for certain requests?

### ISSUE THREAD

**Issue by johnsto** [gorilla/csrf#8]
Say I have an endpoint `/destroy-moon` whereby the credentials of the client are determined by either (a) a secure session value, or (b) the `Authorization` header. I obviously want to use CSRF protection in the first case, but not necessarily in the second. 

The current design means the only way to skip CSRF validation in the second case requires calling `Protect` in the handler every time a request is received. This seems sub-optimal, as the `Protect` call returns a function that performs a fair bit of initialisation that should really only need to be performed once, *not* every request.

The quick solution would be to expose a `func (cs *csrf) Handle(w http.ResponseWriter, r *http.Request, h http.Handler)` function, which, rather than calling the handler `cs.h`, calls the handler `h`. However, this would make the `http.Handler` passed to the func returned by `Protect` completely redundant, and has other ramifications that would upset the nice, clean design of the current library...

So I'm wondering, is this intentional, or have I missed a way to achieve the behaviour I'm after?

**Comment by elithrar** [comment]
Just to lay out the threat model:

1. You issue a user a (reasonably) long-lived access_token
2. They pass it in the headers per-request for authorized requests
3. Because sending a valid Authorization header is controlled by your client (JS app, CLI tool, etc.) rejecting this request is sufficient
4. You *could* also send the CSRF token, but depending on your middleware ordering (Auth => CSRF or CSRF => auth; the latter being preferred) you might have bailed out already.

I still think there's value in sending the CSRF token (the overhead is slim) as another layer of defence should those routes change or your auth middleware has a bug/is removed later. The processing overhead is extremely minimal.

But to address your requirement for "exempting routes" or providing a custom handler to call: I haven't thought of a safe way to approach this with a clean API yet. I very much don't want to go down the path of allowing users to exempt paths (esp. based on regex or globs) as there's a history of people misunderstanding globbing/regex syntax: it's a sharp edge I want to avoid exposing to users.

Just so I can further understand your use case: can you show your router code? The `cs.Handle(w, r, h)` method above would only work in the context of wrapping an individual route. If you're wrapping routes individually with the middleware (rather than with a sub-router approach) you could just create a `nilCSRF := csrf.Protect(nil, csrf.ErrorHandler(yourHandler))` instance and use that. It'll fail straight away and call your handler instead. Not pretty, but functional until we can determine a better long-term approach.

**Comment by johnsto** [comment]
Your understanding is correct - I wrap my routes individually with middleware rather than using sub-routers. Perhaps that is the crux of my problem.

For the moment, I've forked the library and made the appropriate changes to fit my particular use case. The modifications were actually pretty straightforward in the end, as you can see here:
https://github.com/johnsto/csrf/commit/2a302274ecc8e9c58d14eae5ec2380276203d5f7

**Comment by elithrar** [comment]
Alright - I might have a think on how to achieve this. Typically I'd just
apply the middleware at a sub-router level if I was trying to avoid certain
routes (e.g. authenticated routes) which would avoid that issue.

**Comment by elithrar** [comment]
I've added this functionality to the sister library - https://godoc.org/github.com/goji/ctx-csrf#UnsafeSkipCheck - and will  try to find time to port it over to gorilla/csrf this weekend.

**Comment by elithrar** [comment]
Closed via https://github.com/gorilla/csrf/commit/d03564e10380268a4669bb0e5eeeada84413ab51
