### ISSUE TITLE
Set csrf.Path differently based on request

### ISSUE THREAD

**Issue by tuhlmann** [gorilla/csrf#82]
Hi,

is it possible to instruct csrf.Protect() in such a way that I can set the csrf.Path option on a request basis?
I don't want the default behavior (using the request path as cookie path), rather I'd like to check each incoming request path against a list of predefined paths. If the request path contains one of these it would be used, otherwise it'd use the request path.

I found that I can pass a csrf.Path Option to csrf.Protect(), but this option is only parsed once and I didn't find a way to observe the current request for setting the path.

Is it possible to inject this kind of handler/middleware at some point so I can implement this behavior?

Thanks!

**Comment by elithrar** [comment]
`csrf.Path` sets the cookie option, not the path-based piece.

The reason that "route matching" isn't in the public API is that it's a very sharp edge: you likely want CSRF protection on all of your routes. Adding new routes later and forgetting it can be catastrophic.

The most common way to separate it is to use route grouping or subrouting - e.g. https://github.com/gorilla/mux#matching-routes - in your HTTP routing library to apply `csrf.Protect` selectively, making it easier to maintain.

Otherwise, you could wrap it with your own middleware that checks the routes first - e.g.

```go

func SelectivelyApplyCSRFProtection(h http.Handler) http.Handler {
    protect := csrf.Protect(key, csrf.Path("/")) // make sure the cookie path is the parent of all routes
    fn := func(w http.ResponseWriter, r *http.Request) {
        for route, handler := range yourRouteList {
            // test if req.URL matches how you want
            return protect(handler)
     }

     return http.HandlerFunc(fn)
}
```

(this is untested, and you'll likely need to modify it - just giving you some direction here)

**Comment by tuhlmann** [comment]
Thank you for your quick help, I'll look at route grouping.
