### ISSUE TITLE
Multiple Servers Behind Load Balancer

### ISSUE THREAD

**Issue by maxdobeck** [gorilla/csrf#89]
Hi,
This may be an ignorant question but I'm new to implementing my own CSRF token as a middleware. 

How would this work if there were multiple app servers behind load balancer being round robined to?  Is there a redis or database method of storing and verifying the token instead of doing it server side?

Thank you

**Comment by elithrar** [comment]
CSRF tokens are per-request, and thus re-issued on each subsequent request.
Even the issue is round-robin'ing across backends, each application will be
validating its own request : response flow.

Thus CSRF tokens don't need to be server-side, as they are effectively
ephemeral - just validating the requestor is actually making a
non-idempotent (POST, PUT, et. al) request.

**Comment by maxdobeck** [comment]
Thanks for the reply, I have misinterpreted the documentation/implementation.
